create table "User" (
	sno INT,
	customer VARCHAR(50),
	name VARCHAR(50),
	age INT,
	phone VARCHAR(50),
	location VARCHAR(50),
	created_at DATE,
	dummy_data TEXT
);
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (1, 'Gabvine', 'Adolpho De Lasci', 35, '9136085528', '2 Rockefeller Avenue', '2023-02-28T05:44:56Z', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (2, 'Devpoint', 'Lorant Scipsey', 11, '2163454029', '204 Spaight Circle', '2023-11-16T07:24:57Z', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (3, 'Skimia', 'Laughton Readings', 18, '8862435237', '7740 Summit Center', '2023-10-06T00:31:42Z', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (4, 'Brainlounge', 'Marieann Veracruysse', 16, '3286527342', '34437 Tennyson Way', '2024-01-18T23:58:23Z', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (5, 'Tavu', 'Huntlee Dudeney', 49, '6426872269', '278 Michigan Way', '2023-11-27T11:41:15Z', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (6, 'Skiptube', 'Kerwin Signoret', 14, '3112317309', '638 Mayer Parkway', '2023-04-30T19:14:48Z', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (7, 'Muxo', 'Palm Sinnatt', 20, '1138961533', '63 Mockingbird Court', '2023-06-20T20:01:12Z', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (8, 'Leexo', 'Vannie Conn', 28, '4218956566', '2 Dovetail Terrace', '2024-01-05T04:16:13Z', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (9, 'Trudeo', 'Iona Elvidge', 15, '6523186529', '41919 Cottonwood Crossing', '2023-03-15T05:39:14Z', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (10, 'Rhycero', 'Aeriel Stangoe', 17, '4413122007', '891 Vahlen Street', '2023-10-11T19:27:40Z', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (11, 'Photojam', 'Lurline Peat', 32, '3138714344', '0328 Vahlen Street', '2023-08-15T15:13:40Z', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (12, 'Mydeo', 'Ronica Cranidge', 26, '8006575666', '40 Beilfuss Street', '2023-03-10T00:05:34Z', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (13, 'Dabfeed', 'Gerti Galsworthy', 34, '9942856600', '2827 Beilfuss Lane', '2023-11-06T05:19:16Z', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (14, 'Zava', 'Sebastien McMinn', 46, '1848966931', '21 Dixon Court', '2023-10-12T08:50:18Z', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (15, 'Skajo', 'Philbert Grave', 42, '9844128062', '83 Arizona Junction', '2023-11-24T14:10:03Z', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (16, 'Livepath', 'Raf Hinken', 21, '8483372725', '2 Oneill Lane', '2024-02-23T13:26:11Z', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (17, 'Bubblemix', 'Armin Seabrooke', 11, '1557846452', '6 Gale Circle', '2024-01-30T16:35:45Z', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (18, 'Dabtype', 'Bennie Marchetti', 23, '4418780618', '81645 Dovetail Terrace', '2023-06-24T14:08:31Z', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (19, 'Zoovu', 'Celka Laffoley-Lane', 12, '8618043003', '7 2nd Crossing', '2023-03-08T07:47:28Z', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (20, 'Mymm', 'Wandie Jakubovitch', 52, '9498557430', '6537 Melody Trail', '2023-12-04T23:54:54Z', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (21, 'Jayo', 'Paule Hawkett', 25, '5435553887', '5844 Beilfuss Avenue', '2023-04-22T04:03:31Z', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (22, 'Jaxspan', 'Julio Valente', 25, '7305521494', '43772 Mayer Parkway', '2023-09-02T21:04:10Z', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (23, 'Gabspot', 'Rowland Maben', 32, '3543339523', '058 Reinke Road', '2023-08-05T16:48:22Z', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (24, 'Devshare', 'Collie McCarver', 17, '8559898702', '52591 Blackbird Lane', '2023-03-28T19:59:30Z', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (25, 'Twitterbridge', 'Alameda Vossgen', 44, '3737199957', '206 Lukken Crossing', '2023-02-28T08:20:40Z', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (26, 'Wikivu', 'Lissy Craigs', 26, '4801394949', '7 Roxbury Court', '2023-12-08T02:21:53Z', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (27, 'Meezzy', 'Frederick Blaase', 40, '4053705967', '8806 East Circle', '2023-10-09T03:36:05Z', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (28, 'Ainyx', 'Katha Grabban', 37, '9734841614', '4330 Independence Pass', '2023-12-28T17:11:30Z', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (29, 'Latz', 'Joycelin Pilkinton', 59, '1234281165', '18 Longview Center', '2023-11-29T17:54:34Z', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (30, 'Tagtune', 'Kippie Indgs', 39, '4319256393', '473 Maryland Park', '2023-09-19T17:15:37Z', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (31, 'Realcube', 'Myrah Alkin', 56, '2943245751', '1251 Londonderry Terrace', '2024-01-16T02:19:22Z', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (32, 'Trilia', 'Gnni Spriggen', 57, '9293958413', '0426 Ludington Way', '2024-01-11T09:00:30Z', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (33, 'Realcube', 'Marybelle Choules', 57, '2121251807', '1 Judy Road', '2023-03-29T05:08:36Z', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (34, 'Quatz', 'Aron Yellowley', 45, '2134947042', '9412 Bunting Way', '2023-03-09T19:22:05Z', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (35, 'Aibox', 'Rana Orht', 34, '9922656762', '857 Oriole Road', '2023-07-04T08:16:47Z', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (36, 'Trupe', 'Nicol Lyttle', 13, '8205058453', '89101 Fair Oaks Road', '2023-05-16T12:01:36Z', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (37, 'Linklinks', 'Almire Glashby', 23, '5837052491', '06 Mayer Road', '2023-05-01T16:31:49Z', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (38, 'Innojam', 'Hally Curm', 39, '1845636470', '23598 Springs Circle', '2023-10-26T05:12:34Z', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (39, 'Vinte', 'Hilary Geraghty', 45, '4071961533', '0009 Anderson Trail', '2023-05-31T03:34:16Z', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (40, 'Oyope', 'Robenia Presshaugh', 28, '7649149713', '948 Transport Circle', '2023-08-30T10:06:35Z', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (41, 'Skippad', 'Cele Tinker', 16, '2596799179', '78 Pond Street', '2023-03-01T02:19:19Z', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (42, 'Edgetag', 'Raoul Plaschke', 51, '3918791890', '23328 Reinke Circle', '2023-12-02T06:10:18Z', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (43, 'Zoombox', 'Miguela Hamilton', 18, '3001375073', '8285 Sommers Crossing', '2023-04-03T16:04:22Z', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (44, 'Zoomlounge', 'Billie Rushton', 27, '6945951589', '01463 Kropf Trail', '2023-08-18T18:56:53Z', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (45, 'Trilith', 'Avie Brunelli', 26, '6546147290', '98654 Westend Circle', '2024-02-19T05:50:39Z', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (46, 'Dynazzy', 'Cassey Harpur', 42, '1029652615', '4 Charing Cross Avenue', '2024-01-07T23:21:10Z', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (47, 'Jaxspan', 'Kala Daudray', 53, '7429356856', '6799 Mayfield Drive', '2023-09-05T18:45:05Z', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (48, 'Linkbridge', 'Gail Blyth', 22, '2263666858', '8071 Gateway Plaza', '2024-02-25T04:16:34Z', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (49, 'Centidel', 'Paulina Ericssen', 37, '5272742789', '8170 Brentwood Avenue', '2024-02-10T06:14:24Z', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.');
insert into "User" (sno, customer, name, age, phone, location, created_at, dummy_data) values (50, 'Jaxbean', 'Joell Screas', 38, '1282575062', '3528 Everett Circle', '2023-10-09T16:12:17Z', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
